services:
  ffmpeg-tool:
    build:
      context: .
    container_name: ffmpeg-cdn-load-tester
    command: python app.py --help
    volumes:
      - ./data:/data
    environment:
      PYTHONUNBUFFERED: "1"
